//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "course")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub no: String,
    pub name: String,
    pub precourse: Option<String>,
    pub credit: Option<i32>,
    pub dno: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Precourse",
        to = "Column::No",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::department::Entity",
        from = "Column::Dno",
        to = "super::department::Column::No",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Department,
    #[sea_orm(has_many = "super::sc::Entity")]
    Sc,
}

impl Related<super::department::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Department.def()
    }
}

impl Related<super::sc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sc.def()
    }
}

impl Related<super::student::Entity> for Entity {
    fn to() -> RelationDef {
        super::sc::Relation::Student.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::sc::Relation::Course.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
