//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::course::Entity as Course;
pub use super::department::Entity as Department;
pub use super::sc::Entity as Sc;
pub use super::student::Entity as Student;
