//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::course::Entity as Course;
pub use super::department::Entity as Department;
pub use super::score::Entity as Score;
pub use super::student::Entity as Student;
pub use super::users::Entity as Users;
